name: Lint

on:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Check Types
        run: pnpm types:check

      - name: Run ESLint
        run: pnpm lint
